name: Batch Git Clone and Upload

on:
  workflow_dispatch:

jobs:
  batch_clone_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 克隆镜像
      run: |
        git clone https://github.com/istoreos/istoreos.git
    - name: 环境准备
      run: |
          #sudo rm -rf /usr/share/dotnet /etc/mysql /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
          #sudo -E apt-get -y purge ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* php* android*
          sudo -E apt-get update
          sudo apt-get install subversion g++ zlib1g-dev build-essential git \
          python3 python3-distutils libncurses5-dev gawk gettext unzip \
          file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

    - name: 更新软件包
      run: |
        ls
        cd ./istoreos
        ls
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 创建Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0
        release_name: Release v1.0
        body: |
          Description of the release
        draft: false
        prerelease: false

    - name: 上传到Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./istoreos
        asset_name: openwrt.zip
        asset_content_type: application/gzip
        
    - name: 删除workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: 删除老的Releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
